multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "bk_solver.py", line 69, in evolve
    k2 = dblquad(func, xr1, xr2, 0.0, 0.5 * np.pi, epsabs=0.0, epsrel=0.05, args=(0.5 * hy * k1,))
TypeError: can't multiply sequence by non-int of type 'float'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bk_solver.py", line 149, in <module>
    bk = master(float(p[0]), float(p[1]), float(p[2]), float(p[3]), p[4])
  File "bk_solver.py", line 108, in master
    xk = pool.map(evolve, xlr_, chunksize=80)
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
TypeError: can't multiply sequence by non-int of type 'float'
